spring.application.name=cliente-service
server.port=9091

# Base de datos propia (Punto 2)
spring.datasource.url=jdbc:mysql://localhost:3306/bd_cliente?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog-master.xml

# Habilitar Logging (Punto 9 de la rúbrica)
logging.level.com.example.cliente_service=DEBUG