spring.application.name=asistencia-service
server.port=9095
spring.datasource.url=jdbc:mysql://localhost:3306/bd_asistencia?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog-master.xml
logging.level.com.example.asistencia_service=DEBUG
