spring.application.name=empleado-service
server.port=9092
spring.datasource.url=jdbc:mysql://localhost:3306/bd_empleado?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog-master.xml
logging.level.com.example.empleado_service=DEBUG
